services:

  db:
    image: postgres:13
    container_name: postgres_db_ruben
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    networks:
      - admin_web_traefik
    ports:
      - "5439:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  node:
    image: ruben2611/nodejs_postgres:latest
    container_name: nodejs_app_ruben
    depends_on:
      - db
    ports:
      - "3026:3000"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/mydb
      - NODE_ENV= production
    restart: unless-stopped
    command: ["npm", "run", "start"]
    networks:
      - admin_web_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ruben.rule=Host(`ruben.soudry-ort.online`)"
      - "traefik.http.routers.ruben.entrypoints=web"
      - "traefik.http.services.ruben.loadbalancer.server.port=3000"
      - "traefik.http.routers.karate-http.rule=Host(`ruben.soudry-ort.online`)"
      - "traefik.http.routers.karate-http.entrypoints=web"
      - "traefik.http.routers.karate-http.middlewares=redirect-to-https"

volumes:
  db_data:

networks:
  admin_web_traefik:
    external: true