services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik_ruben"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:81"
    ports:
      - "81:81"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ".:/etc/traefik"
    networks:
      - web_ruben


  db:
    image: postgres:13
    container_name: postgres_db_ruben
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    networks:
      - web_ruben
    ports:
      - "5439:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  node:
    image: ruben2611/nodejs_postgres:latest
    container_name: nodejs_app_ruben
    depends_on:
      - db
    ports:
      - "3026:3000"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/mydb
      - NODE_ENV= production
    restart: unless-stopped
    command: ["npm", "run", "start"]
    networks:
      - web_ruben
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`ruben.soudry-ort.online`)"
      - "traefik.http.routers.node.entrypoints=web"
      - "traefik.http.services.node.loadbalancer.server.port=3000"

volumes:
  db_data:

networks:
  web_ruben:
    driver: bridge